dark-deal-dialogue
pokerogue-KO/ME-KOREAN pull request #1
Opened 2024-09-12 12:04 UTC by sodaMelon

2024-09-13 14:17 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "title": "암거래",
여기서는 dark의 의미를 살려서 암거래보다는 "어둠의 거래"가 낫지 않을까 싶습니다. 암거래라고 하면 뭔가 보약이나 그런거 거래하는 것 같기도 하고요..ㅋㅋㅋ

2024-09-13 14:17 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "intro_dialogue": "거기, 너!$$난 포켓몬의 잠재된 힘을 끌어낼 수 있는\n새로운 장치를 개발 중이거든!$분자 수준에서 포켓몬의 원자를\n훨씬 더 강력한 형태로 완전히 재결합시키는 거야.$히히...@d{64} 약간의 희생- 아니@d{32}\n음, 증명을 도와줄 테스트 대상을 찾고 있어.`",
$가 두 개 사용된 이유가 있나요?

2024-09-13 14:17 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +      "selected_message": "남자는 로그볼 5개를 건넸다.${{pokeName}}는(은) 이상한 기계에 들어갔다...$불빛이 깜빡이고 이상한 소음이\n기계에서 들려온다!$...@d{96} 장치에서 무언가가\n맹렬한 기세로, 뛰쳐나왔다!"
```suggestion
      "selected_message": "남자는 로그볼 5개를 건넸다.${{pokeName}}는(은) 이상한 기계에 들어갔다...$불빛이 깜빡이고 이상한 소음이\n기계에서 들려온다!$...@d{96} 장치에서 무언가가\n맹렬한 기세로 뛰쳐나왔다!"
```
쉼표는 빼도 될 듯합니다

2024-09-13 14:19 UTC, returntoice requested changes

2024-09-13 14:19 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +      "selected_dialogue": "어디 보자, {{pokeName}}가(이) 좋겠군!$명심해, 나쁜 일이 생겨도\n책임 못 지니까!@d{32} 히히...",
```suggestion
      "selected_dialogue": "어디 보자, {{pokeName}}[[가]] 좋겠군!$명심해, 나쁜 일이 생겨도\n책임 못 지니까!@d{32} 히히...",
```

2024-09-13 14:19 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +      "selected_message": "남자는 로그볼 5개를 건넸다.${{pokeName}}는(은) 이상한 기계에 들어갔다...$불빛이 깜빡이고 이상한 소음이\n기계에서 들려온다!$...@d{96} 장치에서 무언가가\n맹렬한 기세로, 뛰쳐나왔다!"
```suggestion
      "selected_message": "남자는 로그볼 5개를 건넸다.${{pokeName}}[[는]] 이상한 기계에 들어갔다...$불빛이 깜빡이고 이상한 소음이\n기계에서 들려온다!$...@d{96} 장치에서 무언가가\n맹렬한 기세로, 뛰쳐나왔다!"
```

2024-09-13 14:54 UTC, KimJeongSun requested changes
나레이션은 과거형 ~했다 로 통일했고
번역투를 줄이는 방향으로 수정했습니다. 주관적일수있으니 다들 의견주세요 🙇

2024-09-13 14:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "intro": "너덜너덜한 외투를 입은 낯선 남자가\n당신을 막아섭니다....",
```suggestion
  "intro": "너덜너덜한 외투를 입은\n이상한 남자가 길을 막았다....",
```

2024-09-13 14:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "speaker": "수상한 사람",
```suggestion
  "speaker": "수상한 남자",
```

2024-09-13 14:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "intro_dialogue": "거기, 너!$$난 포켓몬의 잠재된 힘을 끌어낼 수 있는\n새로운 장치를 개발 중이거든!$분자 수준에서 포켓몬의 원자를\n훨씬 더 강력한 형태로 완전히 재결합시키는 거야.$히히...@d{64} 약간의 희생- 아니@d{32}\n음, 증명을 도와줄 테스트 대상을 찾고 있어.`",
```suggestion
  "intro_dialogue": "거기, 너!$$난 포켓몬의 숨겨진 힘을 끌어낼 수 있는\n새로운 장치를 만드는 중이거든!$포켓몬을 분자 수준에서 재결합해서 훨씬 더 강력한 형태로 만드는거야.$히히...@d{64} 이걸 증명하려면 약간의 희ㅅ- 아니@d{32}음, 실험 대상이 필요해.",
```
잘못추가된 ` 제거했습니다.

2024-09-13 14:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "description": "불청객이 볼을 여러 개 들고 있군요.\n\"내가 보답한다니까! 이 강력한 몬스터볼을 대가로 줄 테니까, 너희 팀의 포켓몬을 한 마리 줘! 히히",
```suggestion
  "description": "기분 나쁜 남자는 몬스터볼을 여러 개 들고있다.\n\"내가 보장할게! 네 포켓몬을 한 마리만 줘! 대신 아주 좋은 몬스터볼을 줄 테니까. 히히\"",
```
\"\"로 감싸진 부분 누락을 수정했습니다.

2024-09-13 14:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +      "selected_message": "남자는 로그볼 5개를 건넸다.${{pokeName}}는(은) 이상한 기계에 들어갔다...$불빛이 깜빡이고 이상한 소음이\n기계에서 들려온다!$...@d{96} 장치에서 무언가가\n맹렬한 기세로, 뛰쳐나왔다!"
```suggestion
      "selected_message": "남자는 로그볼 5개를 건넸다.${{pokeName}}[[는]] 이상한 기계에 들어갔다...$표시등이 깜빡이고 이상한 소리가\n기계에서 들려오기 시작했다!$...@d{96} 기계에서 뭔가가\n맹렬한 기세로, 뛰쳐나왔다!"
```

2024-09-13 14:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +      "selected": "불쌍한 사람을 도와주지 않는 거야?\n하!"
```suggestion
      "selected": "불쌍한 사람을 그냥 지나칠거야?\n하!"
```

2024-09-13 14:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "outro": "끔찍한 조우는 끝났고,\n당신은 마음을 다잡고 나아간다."
```suggestion
  "outro": "꺼림직한 만남을 뒤로 하고,\n침착하게 자리를 떠났다."
```
이부분은 사실 끔찍하긴 하지만, 선택지를 안고르면 그냥 끔찍한 은 좀 과한 뉘앙스라서 둘다 커버하는 꺼림직하다는 표현으로 썼습니다.

2024-09-13 15:01 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "title": "암거래",
```suggestion
  "title": "수상한 거래",
```

2024-09-13 15:06 UTC, Le-KaaN commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "intro": "너덜너덜한 외투를 입은 낯선 남자가\n당신을 막아섭니다....",
speaker가 수상한 남자라 이상한보단 수상한으로 통일하는게 좋을 것 같습니다

2024-09-13 15:18 UTC, Le-KaaN commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "outro": "끔찍한 조우는 끝났고,\n당신은 마음을 다잡고 나아간다."
이 부분도 수상한 쪽으로 방향을 잡을거라면 수상한 만남으로 해도 될 것 같습니다.

2024-09-13 15:37 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "intro": "너덜너덜한 외투를 입은 낯선 남자가\n당신을 막아섭니다....",
이거는 저는 소다님이 하신 "낯선"이 좋다고 생각합니다. 대상이 명확히 구별되는 이상 형용사를 전부 통일할 필요는 없고, 처음 마주한 상황이라 strange가 이상하다는 의미보다는 stranger 할 때 strange의 의미 같아서요

2024-09-13 15:37 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "outro": "끔찍한 조우는 끝났고,\n당신은 마음을 다잡고 나아간다."
꺼림직한으로 번역하는 것 좋은 듯합니다

2024-09-13 15:44 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "intro": "너덜너덜한 외투를 입은 낯선 남자가\n당신을 막아섭니다....",
저는 이상한 을 밀고 싶은게, 사실 ME 모든 NPC 들은 낯선 인물들이라 여기 맥락은 이상한.. 이 맞는것같습니다. 
저사람 보세요 이상하잖습니까 🤣

2024-09-13 15:44 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "outro": "끔찍한 조우는 끝났고,\n당신은 마음을 다잡고 나아간다."
일단은 꺼림직으로

2024-09-14 16:49 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "intro_dialogue": "거기, 너!$$난 포켓몬의 잠재된 힘을 끌어낼 수 있는\n새로운 장치를 개발 중이거든!$분자 수준에서 포켓몬의 원자를\n훨씬 더 강력한 형태로 완전히 재결합시키는 거야.$히히...@d{64} 약간의 희생- 아니@d{32}\n음, 증명을 도와줄 테스트 대상을 찾고 있어.`",
아녀 이거 실수입니다

2024-09-14 16:49 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "intro_dialogue": "거기, 너!$$난 포켓몬의 잠재된 힘을 끌어낼 수 있는\n새로운 장치를 개발 중이거든!$분자 수준에서 포켓몬의 원자를\n훨씬 더 강력한 형태로 완전히 재결합시키는 거야.$히히...@d{64} 약간의 희생- 아니@d{32}\n음, 증명을 도와줄 테스트 대상을 찾고 있어.`",
```suggestion
  "intro_dialogue": "거기, 너!$난 포켓몬의 잠재된 힘을 끌어낼 수 있는\n새로운 장치를 개발 중이거든!$분자 수준에서 포켓몬의 원자를\n훨씬 더 강력한 형태로 완전히 재결합시키는 거야.$히히...@d{64} 약간의 희생- 아니@d{32}\n음, 증명을 도와줄 테스트 대상을 찾고 있어.`",
```

2024-09-14 16:49 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "description": "불청객이 볼을 여러 개 들고 있군요.\n\"내가 보답한다니까! 이 강력한 몬스터볼을 대가로 줄 테니까, 너희 팀의 포켓몬을 한 마리 줘! 히히",
```suggestion
  "description": "수상한 남자가 몬스터볼을 여러 개 들고 있습니다.\n\"내가 보장할게! 네 포켓몬을 한 마리만 줘! 대신 아주 좋은 몬스터볼을 줄 테니까. 히히\"",
```
위에서 습니다 체로 바꿨어요

2024-09-14 16:50 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "intro_dialogue": "거기, 너!$$난 포켓몬의 숨겨진 힘을 끌어낼 수 있는\n새로운 장치를 만드는 중이거든!$포켓몬을 분자 수준에서 재결합해서 훨씬 더 강력한 형태로 만드는거야.$히히...@d{64} 이걸 증명하려면 약간의 희ㅅ- 아니@d{32}음, 실험 대상이 필요해.",
```suggestion
  "intro_dialogue": "거기, 너!$난 포켓몬의 숨겨진 힘을 끌어낼 수 있는\n새로운 장치를 만드는 중이거든!$포켓몬을 분자 수준에서 재결합해서 훨씬 더 강력한 형태로 만드는거야.$히히...@d{64} 이걸 증명하려면 약간의 희ㅅ- 아니@d{32}음, 실험 대상이 필요해.",
```

2024-09-14 16:53 UTC, sodaMelon commented
1차 마무리 완료

2024-09-14 17:05 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +      "label": "승낙",
```suggestion
      "label": "승낙한다",
```

2024-09-14 17:05 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +      "label": "거절",
```suggestion
      "label": "거절한다",
```

2024-09-15 02:05 UTC, KimJeongSun commented
https://github.com/user-attachments/assets/25bdcafd-545d-441d-8493-315844896660

2024-09-15 02:05 UTC, merged