[event] strong stuff, pokemon salesman
pokerogue-KO/ME-KOREAN pull request #16
Opened 2024-09-17 14:56 UTC by sodaMelon

# 강력한 물건
단단지가 항상 고정이 될지는 모르겠는 이벤트입니다.
특별한 점은 없네요

# 포켓몬 상인
사기꾼 할아버지(비주얼: 노신사)입니다.
특이한 점은
이벤트 설명창(textarea)에서도
이벤트 설명이 아닌 노인의 대사를 "대사입니다" <-로 말하고 있어요.

2024-09-17 18:27 UTC, returntoice requested changes

2024-09-17 18:27 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-pokemon-salesman-dialogue.json
> +  "intro": "건장한 노신사가 다가왔다.",
```suggestion
  "intro": "쾌활한 노신사가 다가왔다.",
```
chipper의 의미가 heerful and lively라고 되어 있어서 쾌활 정도가 어떨까 합니다..

2024-09-17 18:27 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-pokemon-salesman-dialogue.json
> +  "description_shiny": "\"이 {{purchasePokemon}} 매우 독특하며 같은 종에서는 쉽게 볼 수 없는 색을 갖고 있지! 나는 이 좋은 {{purchasePokemon}}[[를]] 자네에게 {{price, money}}에 보내고 싶다네!\"\n\n\"어떻게 생각하시오?\"",
```suggestion
  "description": "\"이 {{purchasePokemon}}[[는]] 매우 독특하며 같은 종에서는 쉽게 볼 수 없는 특성을 갖고 있지! 나는 이 좋은 {{purchasePokemon}}[[를]] 자네에게 {{price, money}}에 보내고 싶다네!\"\n\n\"어떻게 생각하는가?\"",
  "description_shiny": "\"이 {{purchasePokemon}} 매우 독특하며 같은 종에서는 쉽게 볼 수 없는 색을 갖고 있지! 나는 이 좋은 {{purchasePokemon}}[[를]] 자네에게 {{price, money}}에 보내고 싶다네!\"\n\n\"어떻게 생각하는가?\"",
```
앞 문장은 하게체고 뒷 문장은 하오체라서 하게체로 통일했습니다.

2024-09-17 18:27 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-pokemon-salesman-dialogue.json
> +      "selected_message": "터무니 없는 가격을 내고 {{purchasePokemon}}[[를]] 데려왔다.",
```suggestion
      "selected_message": "터무니없는 가격을 내고 {{purchasePokemon}}[[를]] 데려왔다.",
```

2024-09-17 18:27 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-pokemon-salesman-dialogue.json
> +      "selected_dialogue": "탁월한 선택이로군!$자네는 비즈니스에 대한 안목이 있구만.$오호…@d{64} 반품은 안된다네, 알고 있겠지?"
```suggestion
      "selected_dialogue": "탁월한 선택이로군!$자네는 비즈니스에 안목이 있구먼.$오호…@d{64} 반품은 안 된다네. 알고 있겠지?"
```

2024-09-17 18:27 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
> +  "intro": "커다란 {{shuckleName}}를 만났다!\n마시고 있는 심상치 않아보이는 주스는 뭘까…?",
```suggestion
  "intro": "커다란 {{shuckleName}}를 만났다!\n마시고 있는 심상치 않아 보이는 주스는 뭘까…?",
```

2024-09-17 18:27 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
> +  "description": "당신을 막아선 {{shuckleName}}[[는]] 엄청나게 강해보입니다. 게다가, 그 옆에 있는 주스는 무언가 기운이 느껴지는 것 같습니다.\n\n{{shuckleName}}가 당신 쪽으로 발을 내밉니다. 무언가 하려는 모양입니다…",
```suggestion
  "description": "당신을 막아선 {{shuckleName}}[[는]] 엄청나게 강해보입니다. 게다가 그 옆에 있는 주스에서는 무언가 기운이 느껴지는 것 같습니다.\n\n{{shuckleName}}가 당신 쪽으로 발을 내밉니다. 무언가 하려는 모양입니다…",
```

2024-09-17 18:27 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
> +      "selected_2": "@f{150}정신을 차리고 나니, {{shuckleName}}[[는]] 사라지고\n주스도 완전히 사라졌다.${{highBstPokemon1}}[[과]] {{highBstPokemon2}}[[는]]\n굉장히 무기력해졌다!$두 포켓몬의 기본 능력치가 {{reductionValue}}만큼 감소했다!$하지만 남은 다른 포켓몬
```suggestion
      "selected_2": "@f{150}정신을 차리고 나니, {{shuckleName}}[[는]] 사라지고\n주스도 완전히 비었다.${{highBstPokemon1}}[[과]] {{highBstPokemon2}}[[는]]\n굉장히 무기력해졌다!$두 포켓몬의 기본 능력치가 {{reductionValue}}만큼 감소했다!$하지만 다른 포켓몬들은 놀라울만큼 활력이 넘친다!\n다른 포켓몬의 기본 능력치가 {{increaseValue}}만큼 증가했다!"
```
1) drain의 의미를 조금 살려 보았습니다.
2) remaining의 사전적 의미는 '남은'이지만 한국어 문장상 '다른'만 써도 의미가 통할 듯합니다.

2024-09-17 18:27 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
> +      "selected": "화가난 {{shuckleName}}[[가]] 주스를 마시고 공격해왔다!",
```suggestion
      "selected": "화가 난 {{shuckleName}}[[가]] 주스를 마시고 공격해 왔다!",
```

2024-09-17 18:27 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
> +  "outro": "기묘한 반전 이벤트를 겪었다…."
```suggestion
  "outro": "이 무슨 기묘한 전개인가…."
```
event는 그냥 '일'이나 '사건'으로 보는 게 낫지 않을까 싶습니다.

2024-09-17 18:37 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
> +  "outro": "기묘한 반전 이벤트를 겪었다…."
```suggestion
  "outro": "기묘한 일을 겪은 것 같다…."
```
좀 더 자연스러운 표현으로 교체해둘게요! 감사합니다~

2024-09-18 04:40 UTC, KimJeongSun commented
Strong Stuff

https://github.com/user-attachments/assets/41bc7368-4b99-4948-9359-40a59ca2dcb7

Salesman

https://github.com/user-attachments/assets/85f1302d-4343-4a36-8478-4e9505fb12c6

https://github.com/user-attachments/assets/073a851c-ee1c-42df-8ab5-8a6d64c6d03b

2024-09-18 04:58 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/the-pokemon-salesman-dialogue.json
> +      "selected": "아니?@d{32} 거절하겠다고?$요즘 젊은이들은\n호의를 베풀어도 받을 줄을 모른다니까!"
```suggestion
      "selected": "아니?@d{32} 거절하겠다고?$요즘 젊은이들은\n호의를 베풀어도 모른다니까!"
```

2024-09-18 05:00 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
> +      "selected_2": "@f{150}정신을 차리고 나니, {{shuckleName}}[[는]] 사라지고\n주스도 완전히 비었다.${{highBstPokemon1}}[[과]] {{highBstPokemon2}}[[는]]\n굉장히 무기력해졌다!$두 포켓몬의 종족값이 {{reductionValue}}만큼 줄어들었다!$하지만 다른 포켓몬들은 놀라울
```suggestion
      "selected_2": "@f{150}정신을 차리고 나니, {{shuckleName}}[[는]] 사라지고\n주스도 완전히 비었다.${{highBstPokemon1}}[[과]] {{highBstPokemon2}}[[는]]\n굉장히 무기력해졌다!$두 포켓몬의 종족값이 {{reductionValue}}만큼 감소했다!$하지만 다른 포켓몬들은 놀라울만큼 활력이 넘친다!\n다른 포켓몬의 종족값이 {{increaseValue}}만큼 증가했다!"
```

2024-09-18 05:00 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
> +      "selected_2": "@f{150}정신을 차리고 나니, {{shuckleName}}[[는]] 사라지고\n주스도 완전히 비었다.${{highBstPokemon1}}[[과]] {{highBstPokemon2}}[[는]]\n굉장히 무기력해졌다!$두 포켓몬의 종족값이 {{reductionValue}}만큼 줄어들었다!$하지만 다른 포켓몬들은 놀라울
아침에일어나니 명확한 표현이 보여서.. 고쳐둡니다

2024-09-18 05:00 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
> +      "stat_boost": "주스로 {{shuckleName}}의 능력치가 올라갔다!"
```suggestion
      "stat_boost": "주스를 마신 {{shuckleName}}의 능력치가 올라갔다!"
```

2024-09-18 05:01 UTC, merged