[event] teleporting hijinks, slumbering snorlax
pokerogue-KO/ME-KOREAN pull request #17
Opened 2024-09-17 15:46 UTC by sodaMelon

- 텔레포트 대소동
하이징크스가..좀...? 해석이 애매하네요

- 잠자는 잠만보
특별한 건 없어보입니다

2024-09-17 18:03 UTC, returntoice requested changes

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/slumbering-snorlax-dialogue.json
> +  "intro": "좁은 길을 걷다보니, 우뚝 솟은 거대한 실루엣이 길을 막고 있는 것을 발견했다.$가까이 다가가보니, 평화롭게 자고있는 {{snorlaxName}}이다.\n피할 수 있는 방법은 없는 것 같다….",
```suggestion
  "intro": "좁은 길을 걷다보니 거대한 실루엣이 길을 막고 있는 것을 발견했다.$가까이 다가가 보니 평화롭게 자고있는 {{snorlaxName}}이다.\n피할 수 있는 방법은 없는 것 같다….",
```
1) 쉼표는 빼는 편이 자연스러울 듯합니다. 어법상 틀리지는 않지만 짧은 문장의 경우 쉼표를 넣으면 호흡이 끊겨서 약간 어색하게 느껴집니다.. 표준국어대사전의 용례에서도 '-니'에서는 쉼표를 쓰지 않는 문장들을 소개하고 있고요.
2) towering이라는 단어가 뭔가 높이 솟아 있는 느낌이긴 한데, 잠만보가 누워 있는 모습을 생각했을 땐 그냥 '거대한' 정도로만 처리하는 게 오히려 우리말로 했을 때 더 와닿지 않을까 싶습니다.

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/slumbering-snorlax-dialogue.json
> +  "description": "공격해서 자리를 비키게 할 수도, 잠에서 깨어날 때까지 기다릴 수도 있습니다. 하지만 얼마나 오래 걸릴지는 알 수 없겠지만요….",
```suggestion
  "description": "공격해서 자리를 비키게 할 수도, 잠에서 깨어날 때까지 기다릴 수도 있습니다. 얼마나 기다려야 할지는 알 수 없겠지만요….",
```
그냥 '걸린다'라고만 하면 앞(공격하는 것)에도 해당이 되는 것처럼 읽힐 수도 있을 듯하여 '기다리다'로 맞추어 주는 게 더 이해하기 쉬울 듯합니다.

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/slumbering-snorlax-dialogue.json
> +      "selected": ".@d{32}.@d{32}.@d{32}$한참을 기다리다보니, {{snorlaxName}}의 하품이 모두를 졸리게 만든다….",
이 부분이나 아래 부분들에 말줄임표(…)와 온점(.)을 같이 쓰신 부분들이 있는데 혹시 이렇게 사용된 이유가 있나요? 앞서 머지한 부분들에서 이렇게 했다든가요....

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/slumbering-snorlax-dialogue.json
> +      "disabled_tooltip": "포켓몬이 특정 기술을 알고 있어야한다.",
```suggestion
      "disabled_tooltip": "포켓몬이 특정 기술을 알고 있어야 한다.",
```

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/slumbering-snorlax-dialogue.json
> +      "selected": "{{option3PrimaryName}}[[는]] {{option3PrimaryMove}}[[를]] 사용했다!$@s{item_fanfare}자고있는 {{snorlaxName}}에게 남아있던 것을\n훔쳐서 도둑처럼 살금살금 도망쳤다!"
```suggestion
      "selected": "{{option3PrimaryName}}[[는]] {{option3PrimaryMove}}[[를]] 사용했다!$@s{item_fanfare}자고 있는 {{snorlaxName}}에게 남아 있던 것을\n훔쳐서 도둑처럼 살금살금 도망쳤다!"
```
보조용언은 붙여 쓰는 것도 허용되지만 띄어 쓰는 것으로 통일하는 게 좋지 않을까 싶습니다.

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +  "description": "기계에는 다음과 같은 표지판이 있습니다:\n  \"사용하려면, 돈을 넣고 캡슐에 들어가세요.\"\n\n어딘가로 당신을 데려다줄 수 있을겁니다…….",
```suggestion
  "description": "기계에는 다음과 같이 설명이 쓰여 있습니다.\n  \"사용하려면 돈을 넣고 캡슐에 들어가세요.\"\n\n기계를 작동시키면 어딘가로 이동할 수 있을 듯하다……",
```
1) 한국어에서는 영어에서처럼 콜론이 사용되지 않다 보니 온점으로 수정했습니다.
2) '표지판'이라는 말이 틀린 건 아니지만, 뭔가 표지판 하면 길이나 상점 같은 데 붙어 있는 큼지막한 판이 먼저 떠오르다 보니 그냥 '설명'이라고 하는 게 자연스럽지 않을까 싶습니다.
3. 'Perhaps it can transport you somewhere' 부분은 기계 설명 부분이 아니라 일반 스크립트라서 하다체로 수정 + 문장을 조금 더 자연스럽게 고쳐 보았습니다.

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +      "selected": "돈을 넣자, 캡슐이 열렸다.\n당신은 안으로 들어갔다……."
```suggestion
      "selected": "돈을 넣자 캡슐이 열렸다.\n당신은 안으로 들어갔다……."
```

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +      "label": "포켓몬의 도움받기",
```suggestion
      "label": "포켓몬의 도움",
```
깔끔하게 그냥 '도움'이라고만 하는 게 더 좋지 않을까 제안합니다.

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +      "disabled_tooltip": "강철 또는 전기 타입 포켓몬이 있어야한다.",
```suggestion
      "disabled_tooltip": "강철 또는 전기 타입 포켓몬이 있어야 한다.",
```

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +      "selected": "{{option2PrimaryName}}의 타입으로 기계의 지불 시스템을 해제했다!$캡슐이 열리자, 당신은 안으로 들어갔다…."
```suggestion
      "selected": "{{option2PrimaryName}}의 타입 덕분에 기계의 지불 시스템을 해제할 수 있었다!$캡슐이 열리자 당신은 안으로 들어갔다…."
```
'타입' 자체를 직접 써서 해제했다고 하기보다는 그 타입이 지닌 여러 능력/특성으로써 해제했다는 뉘앙스 같아서 약간 고쳐 보았습니다. 이 부분은 좀 더 논의해 보면 좋을 듯합니다.

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +      "selected": "기계에서 나오는 깜빡이는 불빛과\n이상한 소리를 푹 빠져서 조사했다…….$정신이 팔려서 야생 포켓몬이\n다가오는 것도 눈치채지 못했다!"
```suggestion
      "selected": "기계에서 나오는 깜빡이는 불빛과\n기묘한 소리에 몰두했다…….$정신이 팔려서 야생 포켓몬이\n다가오는 것도 눈치채지 못했다!"
```
1) strange는 뭔가 여기선 '기묘한'이 더 낫지 않을까 제안해 봅니다
2) '소리를'은 술어와 호응이 되지 않아 고쳤고, 뒤에 술어도 그냥 '몰두하다' 정도로 하면 어떨까 합니다.

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +  "transport": "기계가 심하게 흔들리면서,\n온갖 이상한 소리가 나기 시작했다!$그리고 텔레포트를 시작하자마자, 다시 조용해졌다.",
```suggestion
  "transport": "기계가 심하게 흔들리면서\n온갖 이상한 소리가 나기 시작했다!$그리고 텔레포트를 시작하자마자 다시 조용해졌다.",
```

2024-09-17 18:03 UTC, returntoice commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +  "attacked": "새 바이옴에 도착하자마자, 거기에 있던 야생 포켓몬을 놀래켰다!$야생 포켓몬이 공격해온다!",
```suggestion
  "attacked": "새로운 지역에 발을 내딛자마자 그곳의 야생 포켓몬을 놀라게 했다!$야생 포켓몬이 공격해 왔다!",
```
1) 저도 몰랐는데 방금 사전을 찾아보니 '놀래키다'는 표준어가 아니라 사투리라고 나오네요... 표준어는 '놀라게 하다'='놀래다'라고 합니다
2) 사실 바이옴이긴 한데 원문에는 그냥 area라고 되어 있으니 그걸 살리는 게 좋지 않을까 제안합니다.

2024-09-17 18:11 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/slumbering-snorlax-dialogue.json
> +      "selected": ".@d{32}.@d{32}.@d{32}$한참을 기다리다보니, {{snorlaxName}}의 하품이 모두를 졸리게 만든다….",
이것은 디코에서 말씀드렸듯이…. 가 표준사용법이라서 그렇게 적어뒀어요~!

2024-09-17 18:12 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +  "description": "기계에는 다음과 같은 표지판이 있습니다:\n  \"사용하려면, 돈을 넣고 캡슐에 들어가세요.\"\n\n어딘가로 당신을 데려다줄 수 있을겁니다…….",
3. event description은 설명이라서 ~합니다 로 통일하기로 했어요!

2024-09-17 18:14 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +  "description": "기계에는 다음과 같은 표지판이 있습니다:\n  \"사용하려면, 돈을 넣고 캡슐에 들어가세요.\"\n\n어딘가로 당신을 데려다줄 수 있을겁니다…….",
```suggestion
  "description": "기계에는 다음과 같이 설명이 쓰여 있습니다.\n  \"사용하려면 돈을 넣고 캡슐에 들어가세요.\"\n\n어딘가로 당신을 데려다줄 수 있을겁니다…….",
```

2024-09-17 18:16 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +      "selected": "{{option2PrimaryName}}의 타입으로 기계의 지불 시스템을 해제했다!$캡슐이 열리자, 당신은 안으로 들어갔다…."
전기랑 강철타입만되는데 그냥 부쉈다는 느낌이라서 그렇게 된거같아요ㅋㅋ
이건 반영해둘게요

2024-09-17 18:17 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/slumbering-snorlax-dialogue.json
> +      "selected": ".@d{32}.@d{32}.@d{32}$한참을 기다리다보니, {{snorlaxName}}의 하품이 모두를 졸리게 만든다….",
문장사이에는 …
문장을 끝낼때 사용하면 …. 입니다

2024-09-17 18:19 UTC, sodaMelon reviewed
ice님 제안반영 완료입니다

2024-09-18 05:22 UTC, KimJeongSun commented
텔레포트 대소동

https://github.com/user-attachments/assets/1dac672b-8ffb-41e7-8c25-b2430a3147be


자고있는 잠만보

https://github.com/user-attachments/assets/32cb70c6-4e57-417e-9c38-29ca29206a58

2024-09-18 05:35 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +      "selected": "{{option2PrimaryName}} 덕분에\n결제 시스템을 우회할 수 있었다!$캡슐이 열리자\n당신은 안으로 들어갔다…."
```suggestion
      "selected": "{{option2PrimaryName}} 덕분에\n결제 시스템을 해제할 수 있었다!$캡슐이 열리자\n당신은 안으로 들어갔다…."
```

2024-09-18 05:35 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
> +      "selected": "{{option2PrimaryName}} 덕분에\n결제 시스템을 우회할 수 있었다!$캡슐이 열리자\n당신은 안으로 들어갔다…."
해제/해결(물리)입니다

2024-09-18 05:36 UTC, merged