[other]ME 추가로 인해 변경된 ```src/locales/ko/*.json```
pokerogue-KO/ME-KOREAN pull request #2
Opened 2024-09-12 14:04 UTC by sodaMelon

![image](https://github.com/user-attachments/assets/f1a67e7a-9668-4aef-805d-4de69af742ec)
config.ts 말고 다른 것을 추출했습니다.

번역 완료 상태
- [ ] battle.json
- [ ] bgm-name.json
~~- [ ] config.ts~~
- [ ] dialogue.json
- [ ] egg.json
- [ ] modifier-type.json
- [ ] mystery-encounter-message.json

2024-09-12 14:26 UTC, sodaMelon commented
@KimJeongSun @EnochG1 @returntoice
천천히 봐주세요~ https://github.com/pokerogue-KO/ME-KOREAN/pull/1 얘처럼 번역을해주셔도 되고 
아니면 이런식으로 suggestion 쓸수 있게 올려주시면됩니당

2024-09-13 12:07 UTC, KimJeongSun commented on src/locales/ko/battle.json
> +  "mysteryEncounterAppeared": "What's thi.?"
```suggestion
  "mysteryEncounterAppeared": "뭐지?"
```

2024-09-13 13:31 UTC, KimJeongSun requested changes
대사는 github UI 에서 작업하기 너무 불편해서 나눌게요

2024-09-13 13:31 UTC, KimJeongSun commented on src/locales/ko/battle.json
> +  "mysteryEncounterAppeared": "What's thi.?"
```suggestion
  "mysteryEncounterAppeared": "뭐지?"
```
미스터리 조우 모든 이벤트시 발생하는 첫 메시지입니다. ( 중요 )

2024-09-13 13:31 UTC, KimJeongSun commented on src/locales/ko/egg.json
> +  "eventType": "Mystery Event--/FOR ME ",
```suggestion
  "eventType": "미스터리 이벤트",
```
![image](https://github.com/user-attachments/assets/39fb161d-c579-49b9-8340-0551bce222c6)

미스터리 조우에서 얻는 알에 대한 좌하단 설명 용입니다.

2024-09-13 13:31 UTC, KimJeongSun commented on src/locales/ko/mystery-encounter-messages.json
> +  "cancel_option": "Return to encounter option select.ME"
```suggestion
  "affects_pokedex": "도감에 추가 가능",
  "cancel_option": "조우 선택지로 돌아가기"
```
affect pokedex 는 포켓몬 상인(충격) 에게서 포켓몬을 살때 해당 포켓몬이 도감에 새로 뭔가 추가됨( 숨특, 아마 이로치 )을 표현하는 아이콘에 커서를 올렸을때 나오는 overlay 메시지 입니다. https://github.com/AsdarDevelops/PokeRogue-Events/pull/112
cancel_option 은 Part-Timer and Dancing Lessons 등의 조우시 포켓몬 선택창에서 cancel 키에 hover 했을때 나오는 overlay 메시지 입니다. https://github.com/AsdarDevelops/PokeRogue-Events/pull/139

2024-09-13 14:09 UTC, sodaMelon commented on src/locales/ko/battle.json
> +  "mysteryEncounterAppeared": "What's thi.?"
![image](https://github.com/user-attachments/assets/19858085-5471-469b-b0f2-ac480e9d5aca)

2024-09-13 14:26 UTC, returntoice commented on src/locales/ko/battle.json
> +  "mysteryEncounterAppeared": "What's thi.?"
```suggestion
  "mysteryEncounterAppeared": "어라?"
```

2024-09-13 16:37 UTC, sodaMelon commented
For those who already started to[ translate MEs](https://github.com/pagefaultgames/pokerogue/pull/4183), 3 new entries have been added to ``mystery-encounter-messages.json`` and ``modifier-type.json``, so allow me to ping you to be sure you wont miss them
<@&1258563150584872983>

2024-09-15 15:24 UTC, KimJeongSun commented on src/locales/ko/mystery-encounter-messages.json
> +  "view_party_button": "View Party.ME"
```suggestion
  "view_party_button": "파티 확인"
```

2024-09-15 15:25 UTC, KimJeongSun commented on src/locales/ko/bgm-name.json
> +  "mystery_encounter_gen_6_gts": "XY GTS."
```suggestion
  "mystery_encounter_weird_dream": "PMD EoS Temporal Spire",
  "mystery_encounter_fun_and_games": "PMD EoS Guildmaster Wigglytuff",
  "mystery_encounter_gen_5_gts": "BW GTS",
  "mystery_encounter_gen_6_gts": "XY GTS"
```
이미 미번역 배경음악이 좀 있고 우선순위가 크진 않아서 ME 이후에 몰아서 처리하죠

2024-09-15 16:15 UTC, KimJeongSun commented on src/locales/ko/mystery-encounter-messages.json
> +  "cancel_option": "조우 선택지로 돌아가기"
```suggestion
  "cancel_option": "조우 선택지로 돌아가기",
```

2024-09-15 17:12 UTC, KimJeongSun commented
트레이너 대사, 아이템 설명 및 UI 메시지 번역 초안 작성되었습니다.
트레이너 대사는 말뭉치에서 최대한 찾아서 사용했습니다. ( 일부 대사는 정말 번역이 별로지만, 그래도 본가 대사이니 유지했습니다. )
패배 시 대사는 대부분이 없어서 캐릭터에 맞춰서 새로 작성했습니다.
아이템 설명은 되도록 다른 아이템 대사와 통일감 있게 작성했습니다.
base stat 은 종족값, stats 는 능력치 로 번역했습니다 (공격, 특공 처럼 능력치 자체에는 번역이 따로 없어서, 임의로 능력치 라고 썼습니다 )
배경음악은 이미 미번역 항목들이 ME 전에도 쌓여있기도 하고 우선도가 낮아서, 하더라도 ME 이후에 진행하면 될것같습니다

확인하시고 의견주세요! 내일까지 확인해서 etc 에 대해 merge 진행하겠습니다

2024-09-15 17:28 UTC, KimJeongSun commented on src/locales/ko/modifier-type.json
> +    "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET": { "name": "금색곤충망", "description": "벌레타입 포켓몬을 더 자주 만날 수 있는 행운을 부여한다. 이상하게 무거운 느낌이 든다." }
```suggestion
    "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET": { "name": "금빛곤충망", "description": "벌레타입 포켓몬을 더 자주 만날 수 있는 행운을 부여한다. 이상하게 무거운 느낌이 든다." }
```

2024-09-15 19:02 UTC, sodaMelon commented on src/locales/ko/dialogue.json
> +      "2": "싸우거나 편을 만들거나...\n트레이너들은 좋겠어."
이거 중요한건 아닌데
한국어 폰트는 . <을 전각으로 인식해서
...(분리된 .온점이 3개)인경우는 …(특수문자, 전각1글자)로 쓰긴했어요.
사실 큰 문제는 아닌데 6월2일에 논의된 거라 달아둡니다...

2024-09-15 19:12 UTC, sodaMelon commented on src/locales/ko/modifier-type.json
> +    "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET": { "name": "금빛곤충망", "description": "벌레타입 포켓몬을 더 자주 만날 수 있는 행운을 부여한다. 이상하게 무거운 느낌이 든다." }
```suggestion
    "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET": { "name": "황금 잠자리채", "description": "벌레타입 포켓몬을 더 자주 만날 수 있는 행운을 부여한다. 묘한 무게감이 든다." }
```
2D픽셀 샌드박스게임 : 테라리아 패러디입니다.
무게감이 드는 이유는 
1. 황금잠자리채를 주는 벌레포켓몬 마니아 네 집안 가보입니다. (이벤트 스토리 참고)
2. 테라리아 게임 세계관에서 일단은 황금이라 무거운데...진짜 무거우면, 빠르게 날아다니는 벌레를 속도를 따라 잡을수가없어서(...) ```묘한```을 추천드려요 
![image](https://github.com/user-attachments/assets/529da3ef-d82b-44b4-a982-ab60350a25f7)

https://terraria.fandom.com/ko/wiki/%EC%9E%A0%EC%9E%90%EB%A6%AC%EC%B1%84

2024-09-15 19:30 UTC, sodaMelon commented on src/locales/ko/modifier-type.json
> +    "MYSTERY_ENCOUNTER_BLACK_SLUDGE": { "name": "검은진흙", "description": "악취가 너무 심한 나머지 상점 물건 가격이 크게 비싸진다." },
이건 틀린 건 아닌데!
포켓로그 커뮤니티에 black sludge로 검색하시면 아마 논의가 진행중이예요.
(원래 이효과가 아니었습니다. 결정되면 맞는 쪽으로 변경하던지 아니면 이벤트 스크립트를 변경할게영)

2024-09-15 19:42 UTC, sodaMelon commented on src/locales/ko/modifier-type.json
> +    "MYSTERY_ENCOUNTER_BLACK_SLUDGE": { "name": "검은진흙", "description": "악취가 너무 심한 나머지 상점 물건 가격이 크게 비싸진다." },
이 파일에 있는게 맞대요
(추후에 trash-to-treasure event 스크립트가 바뀐다고 합니다)

2024-09-15 23:52 UTC, returntoice requested changes

2024-09-15 23:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "1": "내 포켓몬들\n싸우고 싶어서 근질근질하고 있었어",
```suggestion
      "1": "내 포켓몬들\n싸우고 싶어서 근질근질하고 있었어.",
```
특별한 경우가 아니라면 대사 스크립트 끝에는 온점을 찍어두는 게 좋지 않을까 싶습니다. 지금 폰이라 한 번에 리뷰가 안 되네요,,

2024-09-15 23:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "2": "내 포켓몬들\n꽤나 개구쟁이라니까"
```suggestion
      "2": "내 포켓몬들\n꽤나 개구쟁이라니까."
```

2024-09-15 23:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "1": "공격하는 것과 방어하는 것\n그 밸런스 유지가 큰일이네",
```suggestion
      "1": "공격하는 것과 방어하는 것\n그 밸런스 유지가 큰일이네.",
```

2024-09-15 23:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "2": "공격하는 것과 방어하는 것\n그 밸런스 유지가 큰일이네"
```suggestion
      "2": "공격하는 것과 방어하는 것\n그 밸런스 유지가 큰일이네."
```

2024-09-15 23:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "1": "이거라면 이 곳에서\n미루가 활약할 수 없을까",
```suggestion
      "1": "이거라면 이곳에서\n미루가 활약할 수 없을까",
```

2024-09-15 23:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "2": "이거라면 이 곳에서\n미루가 활약할 수 없을까"
```suggestion
      "2": "이거라면 이곳에서\n미루가 활약할 수 없을까"
```

2024-09-15 23:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "1": "미루가 이길줄 알았어!",
```suggestion
      "1": "미루가 이길 줄 알았어!",
```

2024-09-15 23:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "2": "미루가 이길줄 알았어!"
```suggestion
      "2": "미루가 이길 줄 알았어!"
```

2024-09-16 01:01 UTC, KimJeongSun commented on src/locales/ko/dialogue.json
> +      "1": "내 포켓몬들\n싸우고 싶어서 근질근질하고 있었어",
원문에서 문장부호 없는 경우가 있어서 빼뒀는데 부호는 알아서 넣어야겠네요

2024-09-16 01:02 UTC, KimJeongSun commented on src/locales/ko/dialogue.json
> +      "2": "이거라면 이 곳에서\n미루가 활약할 수 없을까"
이것도 원문인데 저는 당췌 뭔 번역을 이렇게 했는지 잘 모르겠어요

2024-09-16 01:03 UTC, KimJeongSun commented on src/locales/ko/dialogue.json
> +      "2": "싸우거나 편을 만들거나...\n트레이너들은 좋겠어."
싹 바꿔둘게요

2024-09-16 01:11 UTC, KimJeongSun commented
requested changes 모두 반영해서 마무리합니다 ( 텍스트 테스트는 관련 이벤트에서 겸사겸사 진행하는걸로 할게요 )

2024-09-16 01:11 UTC, merged