[event]an offer you can't refuse, etc..
pokerogue-KO/ME-KOREAN pull request #4
Opened 2024-09-13 13:29 UTC by sodaMelon

.

2024-09-13 13:38 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "selected": "정말 엉망진창인 날이구만....$뭐, 어때. 요트 클럽으로 돌아가자, {{liepardName}}."
```suggestion
      "selected": "정말 시궁창스러운 날이네....$뭐, 어때. 요트 클럽으로 돌아가자, {{liepardName}}."
```

2024-09-13 13:38 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "title": "거절할 수 없는 제안",
원문이랑은 좀 멀어지지만
```거부하기 힘든 제안```
이 좋은것 같긴해보여영 (보류)

2024-09-13 13:48 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "title": "거절할 수 없는 제안",
대부에 나오는 명대사에서 따온걸로 보여서 그대로가 더 자연스러운것같습니다.

2024-09-13 14:36 UTC, returntoice requested changes

2024-09-13 14:36 UTC, returntoice commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "title": "거절할 수 없는 제안",
정선님 말대로 대부 대사 번역이 저걸로 유명하다 보니 저도 정선님 의견에 동의합니다

2024-09-13 14:36 UTC, returntoice commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "description": "당신의 {{strongestPokemon}}에 대해 @[TOOLTIP_TITLE]{Shiny Charm}과 {{price, money}}을 제안 받았다!\n\n매우 좋은 조건이지만, 이렇게 든든한 멤버와 헤어지는 것을 견딜 수 있을까?",
```suggestion
  "description": "당신의 {{strongestPokemon}}[[를]] 넘기는 대가로 @[TOOLTIP_TITLE]{Shiny Charm}과 {{price, money}}을 제안 받았다!\n\n매우 좋은 조건이지만, 이렇게 든든한 멤버와 헤어지는 것을 견딜 수 있을까?",
```

2024-09-13 14:36 UTC, returntoice commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "tooltip": "(-) {{strongestPokemon}}[[를]] 잃음.\n(+) @[TOOLTIP_TITLE]{Shiny Charm}[[를]] 획득.\n(+) {{price, money}}[[를]] 획득",
```suggestion
      "tooltip": "(-) {{strongestPokemon}}[[를]] 잃음.\n(+) @[TOOLTIP_TITLE]{Shiny Charm}[[를]] 획득.\n(+) {{price, money}}[[를]] 획득.",
```

2024-09-13 14:36 UTC, returntoice commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "selected": "말도 안돼. {{liepardName}}, 우리 삥뜯겼어!$이 건에 대해서 변호사를 부를거야!"
```suggestion
      "selected": "말도 안 돼. {{liepardName}}, 우리 삥 뜯겼어!$너, 곧 우리 변호사 연락을 받게 될 거다!"
```
~에 대해서는 뭔가 문어체스러워서 원문대로 가는 게 더 낫지 않을까 조심스레 제안해 봅니다

2024-09-13 15:40 UTC, KimJeongSun requested changes
도련님 느낌이 나도록 수정해봤습니다.

2024-09-13 15:40 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "intro_dialogue": "오늘 운이 좋은 걸.$네 {{strongestPokemon}}[[가]] 정말 멋져서\n눈길이 가는 걸 어쩔 수 없었어!$난 항상 저런 펫이 갖고 싶었거든!$매너있게 값도 지불하고,\n이 골동품도 주도록 하지!",
```suggestion
  "intro_dialogue": "안녕하세요.$당신의 {{strongestPokemon}}[[가]] 정말 멋져서\n그냥 지나칠수가 없네요!$난 항상 저런 애완동물을 갖고 싶었거든요!$제가 오래된 장신구랑 돈도 함께 섭섭지 않게 챙겨주도록 하죠!",
```

2024-09-13 15:40 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "description": "당신의 {{strongestPokemon}}에 대해 @[TOOLTIP_TITLE]{Shiny Charm}과 {{price, money}}을 제안 받았다!\n\n매우 좋은 조건이지만, 이렇게 든든한 멤버와 헤어지는 것을 견딜 수 있을까?",
```suggestion
  "description": "{{strongestPokemon}}[[를]] 넘기는 대신 @[TOOLTIP_TITLE]{Shiny Charm}과 {{price, money}}을 준다고 한다!\n\n매우 좋은 조건이지만, 이렇게 든든한 동료를 보내줘야 할까?",
```

2024-09-13 15:40 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "label": "거래를 받아들인다",
```suggestion
      "label": "제안을 받아들인다",
```

2024-09-13 15:40 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "tooltip": "(-) {{strongestPokemon}}[[를]] 잃음.\n(+) @[TOOLTIP_TITLE]{Shiny Charm}[[를]] 획득.\n(+) {{price, money}}[[를]] 획득",
```suggestion
      "tooltip": "(-) {{strongestPokemon}}[[를]] 보내줌.\n(+) @[TOOLTIP_TITLE]{Shiny Charm}[[를]] 획득.\n(+) {{price, money}}[[를]] 획득.",
```

2024-09-13 15:40 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "selected": "대박!@d{32} 이리와, {{strongestPokemon}}!$요트 클럽 사람들에게 널 자랑해야겠어!$다들 부러워하겠지!"
```suggestion
      "selected": "좋아요!@d{32} 이리와, {{strongestPokemon}}!$요트 클럽에 가서 자랑해야겠어!$다들 엄청 부러워하겠는걸!"
```

2024-09-13 15:40 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "intro": "금수저 소년에게 붙들렸습니다!",
```suggestion
  "intro": "금수저 도련님에게 붙들렸다!",
```

2024-09-13 15:40 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "speaker": "금수저 소년",
```suggestion
  "speaker": "금수저 도련님",
```

2024-09-13 15:40 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "label": "소년을 위협한다",
```suggestion
      "label": "도련님을 위협한다",
```

2024-09-13 15:40 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "selected": "정말 엉망진창인 날이구만....$뭐, 어때. 요트 클럽으로 돌아가자, {{liepardName}}."
```suggestion
      "selected": "정말 실망이네요....$뭐, 어때. 요트 클럽이나 가자, {{liepardName}}."
```

2024-09-13 16:10 UTC, KimJeongSun requested changes
이벤트 이름만 제외하고 나머지 댄스 -> 춤으로 수정했습니다.

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +  "intro": "{{oricorioName}}[[가]] 홀로 외롭게 춤추고 있습니다. 파트너도 없이요!",
```suggestion
  "intro": "{{oricorioName}}[[가]] 슬프게 혼자 춤을 추고 있다.",
```

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +  "description": "{{oricorioName}}[[는]] 공격적이진 않네요. 오히려 슬퍼 보이기까지합니다.\n\n함께 춤출 누군가를 원할지도 모르죠….",
```suggestion
  "description": "{{oricorioName}}[[는]] 공격적으로 보이진 않는다. 오히려 슬퍼 보인다.\n\n춤출 상대를 찾고 있을지도 모른다...",
```

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "selected": "{{oricorioName}}이 춤추는 모습을 가까이서 관찰합니다….$@s{level_up_fanfare}당신의 {{selectedPokemon}}[[는]] {{oricorioName}}에게 배웠다!"
```suggestion
      "selected": "{{oricorioName}}가 춤을 추는 모습을 주의 깊게 지켜보았다….$@s{level_up_fanfare}{{selectedPokemon}}[[는]] {{oricorioName}}에게서 춤을 배웠다!"
```

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "selected": "{{oricorioName}}[[는]] 혼란스러워하며 방어하기 위해 움직입니다!",
```suggestion
      "selected": "{{oricorioName}}[[는]] 혼란스러워하며 방어하기 위해 움직였다!",
```

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "boss_enraged": "{{oricorioName}}[[는]] 겁에 질려 능력치가 상승했습니다!"
```suggestion
      "boss_enraged": "{{oricorioName}}[[는]] 겁에 질려 능력치가 상승했다!"
```

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "disabled_tooltip": "당신의 포켓몬이 댄스 기술을 알아야 합니다.",
```suggestion
      "disabled_tooltip": "포켓몬이 춤 기술을 알고 있어야 한다.",
```

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "select_prompt": "사용할 댄스 기술을 선택합니다.",
```suggestion
      "select_prompt": "사용할 춤 기술을 선택한다.",
```

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "selected": "{{oricorioName}}[[가]] {{selectedPokemon}}[[를]] 선보이는 모습을\n흥미진진하게 지켜봅니다!$마음에 들어하는 것 같아요!$@s{level_up_fanfare}{{oricorioName}}[[가]] 멤버가 되고 싶어합니다!"
```suggestion
      "selected": "{{oricorioName}}[[가]] {{selectedPokemon}}[[를]] 선보이는 모습을\n흥미진진하게 지켜본다!$마음에 들어하는 것 같다!$@s{level_up_fanfare}{{oricorioName}}[[가]] 동료가 되고 싶어 하는 것 같다!"
```

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +  "invalid_selection": "이 포켓몬은 댄스 기술을 알고 있지 않습니다."
```suggestion
  "invalid_selection": "이 포켓몬은 춤 기술을 모른다!"
```

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "label": "댄스를 배운다",
```suggestion
      "label": "춤을 배운다",
```

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "label": "댄스를 보여준다",
```suggestion
      "label": "춤을 보여준다",
```

2024-09-13 16:10 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "tooltip": "(-) {{oricorioName}}에게 댄스 기술을 가르침. \n(+) {{oricorioName}}[[가]] 당신을 좋아함.",
```suggestion
      "tooltip": "(-) {{oricorioName}}에게 춤 기술을 가르침. \n(+) {{oricorioName}}[[가]] 좋아함.",
```

2024-09-13 16:34 UTC, KimJeongSun requested changes

2024-09-13 16:34 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +  "intro": "엄청난 쓰레기 더미입니다!\n어디에서 왔을까요?",
```suggestion
  "intro": "엄청난 쓰레기 더미다!\n도대체 어디서 온 걸까?",
```

2024-09-13 16:34 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +  "title": "쓰레기를 보물로 만들기",
```suggestion
  "title": "쓰레기 속 보물",
```

2024-09-13 16:34 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +  "description": "쓰레기 더미가 눈앞에 펼쳐져있습니다. 그 속에서 가치있는 물건을 찾을 수도 있겠죠. 하지만 그 물건들을 얻기 위해 정말로 오물을 뒤집어쓰고 싶으신가요?",
```suggestion
  "description": "쓰레기 더미 속에 쓸 만한 물건들이 보이는 것 같다. 아무리 그래도 그것 때문에 오물 속으로 들어가야할까?",
```

2024-09-13 16:34 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "label": "쓸만한 것을 발굴한다",
```suggestion
      "label": "쓸만한 것을 뒤져본다",
```

2024-09-13 16:34 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "selected": "당신 쓰레기 더미를 헤집고다니며, 오물을 뒤집어썼다.$그런 지저분한 상태로는, 어느 상점도\n물건을 팔지 않을 것이다!$당신은 앞으로 상점에서 파는 치유 아이템 없이 버텨야한다.$그러나, 당신은 쓰레기에서 놀라운 아이템을 발견했다!"
```suggestion
      "selected": "당신 쓰레기 더미를 헤집고다니며, 오물을 뒤집어썼다.$지금 이 상태로는, 아무리 친절한 점원도\n아무것도 안 팔 것 같다!$앞으로 상점에서 파는 회복약 없이 버텨야 한다.$하지만, 쓰레기에서 엄청난 물건들을 발견했다!"
```

2024-09-13 16:34 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "tooltip": "(-) 상점에서 회복 아이템 구매 불가능\n(+) 놀라운 아이템 획득",
```suggestion
      "tooltip": "(-) 상점에서 회복 아이템 구매 불가능\n(+) 끝내주는 아이템들을 획득",
```

2024-09-13 16:34 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "tooltip": "(?) 쓰레기의 원천을 찾는다",
```suggestion
      "tooltip": "(?) 쓰레기의 근원을 찾는다",
```

2024-09-13 16:34 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "selected": "당신은 쓰레기 더미 주변을 거닐며, 여기에 어떻게 이런 것이 나타날 수 있는지 징후를 찾기 시작했다….",
```suggestion
      "selected": "쓰레기 더미 주변을 거닐며, 이게 여기 어떻게 생겨난건지 단서를 찾아본다...",
```

2024-09-13 16:34 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "selected_2": "S갑자기 쓰레기 더미가 움직였다! 쓰레기가 아니고, 포켓몬이었어!"
```suggestion
      "selected_2": "갑자기 쓰레기 더미가 움직였다! 쓰레기가 아니고, 포켓몬이었다!"
```

2024-09-14 17:01 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "tooltip_disabled": "이 선택지를 선택하려면 포켓몬이 특정 기술이나 능력을 가지고 있어야 합니다.",
```suggestion
      "tooltip_disabled": "이 선택지를 선택하려면 포켓몬이 특정 기술이나 능력을 가지고 있어야 한다.",
```

2024-09-14 17:26 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +  "intro": "{{oricorioName}}[[가]] 홀로 외롭게 춤추고 있습니다. 파트너도 없이요!",
```suggestion
  "intro": "{{oricorioName}}[[가]] 외롭게 혼자 춤을 추고 있다. 주변에 파트너도 없는 것 같다!",
```

2024-09-14 17:29 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "label": "쓸만한 것을 발굴한다",
이것은 나오는 발굴들이 발굴에 가까운......그.검정물질이 나오기때문에
복선으로 그냥 둡니다

2024-09-14 17:29 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "query": "어떻게 할까?",
```suggestion
  "query": "어떻게 하시겠습니까?",
```

2024-09-14 17:29 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +  "query": "무엇을 할까?",
```suggestion
  "query": "무엇을 하시겠습니까?",
```

2024-09-14 17:32 UTC, sodaMelon commented
1차 완료

2024-09-14 17:54 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "selected": "정말 실망이네요....$뭐, 어때. 요트 클럽이나 가자, {{liepardName}}."
```suggestion
      "selected": "재수 없는 날이네요....$뭐, 아무렴 어때. 요트 클럽에 돌아가자, {{liepardName}}."
```

2024-09-15 02:33 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "label": "도련님을 위협한다",
```suggestion
      "label": "꼬마녀석을 혼내준다",
```

2024-09-15 03:25 UTC, KimJeongSun commented
https://github.com/user-attachments/assets/6d3456a9-8695-4865-92b3-660e505d43f9


https://github.com/user-attachments/assets/c834f56f-a83a-4548-9486-e5ddf850928e


https://github.com/user-attachments/assets/8b6b79c1-671f-4406-81d6-90b7a4794e65

2024-09-15 03:25 UTC, merged