[event] berries abound
pokerogue-KO/ME-KOREAN pull request #5
Opened 2024-09-13 16:14 UTC by sodaMelon

# 나무열매 풍년
![image](https://github.com/user-attachments/assets/48ffdb66-f946-48b6-a533-8173cfc24ddb)

스샷 많이 찍어둔거같은데 어디다 백업했는지 기억이 안나네요;
찾으면 갱신해둡니다

2024-09-13 16:15 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/berries-abound-dialogue.json
> +      "selected_bad": "{{fastestPokemon}}[[가]] 나무열매 덤불을 행해 달려간다!$이런! {{enemyPokemon}}[[가]] 더 빨라서, 가로막혔다!",
이 문장 과거형으로 쓰려다가 
원문을 보면 일부러 이렇게 쓴 이유가 좀 있는것 같아서 (로그라이크 연출)
잠깐 대기할게요

2024-09-13 16:16 UTC, sodaMelon reviewed
.

2024-09-13 17:58 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/delibirdy-dialogue.json
> +      "select_prompt": "건네줄 아이템을 선택하세요.",
이건 엔트리 포켓몬에게 도구 건네주기에서도 쓰는 문장이라 그대로 뒀습니다 ~_~

2024-09-13 17:58 UTC, sodaMelon reviewed
.

2024-09-14 07:05 UTC, KimJeongSun requested changes
되도록 원문 의미를 유지하되, 재미를 살릴수있도록 번역했습니다

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/berries-abound-dialogue.json
> +  "intro": "포켓몬 근처에\n열매가 달린 거대한 나무가 있네요!",
```suggestion
  "intro": "포켓몬 근처에 열매가\n달린 거대한 나무가 있다!",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/berries-abound-dialogue.json
> +  "description": "나무열매 덤불을 지키고 있는 강력한 포켓몬이 있는 것 같습니다. 포켓몬 배틀이 간단해보이지만, 조금 강해보이네요. 혹시 빠른 포켓몬이라면 잡히지 않고 열매를 가져올 수 있지 않을까요?",
```suggestion
  "description": "포켓몬이 나무열매 덤불을 지키고 있다. 그냥 싸워볼 수도 있지만, 조금 강해보인다. 혹시 빠른 포켓몬이라면 잡히지 않고 열매를 가져올 수 있지 않을까?",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/berries-abound-dialogue.json
> +      "selected": "당신은 겁도 없이\n포켓몬 앞으로 나아갔다."
```suggestion
      "selected": "용감하게 포켓몬에게 다가갔다."
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/berries-abound-dialogue.json
> +      "label": "덤불을 향한 질주",
```suggestion
      "label": "덤불을 향해 뛴다",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/berries-abound-dialogue.json
> +      "selected": "{{fastestPokemon}}[[가]] 나무열매 덤불을 향해 달려간다!${{enemyPokemon}}[[가]] 반응하기 전에, {{numBerries}}을 획득한다!$당신은 찾은 상품을 들고 재빨리 도망간다.",
```suggestion
      "selected": "{{fastestPokemon}}[[가]] 나무열매 덤불을 향해 달려간다!${{enemyPokemon}}[[가]] 반응하기 전에, {{numBerries}}을 낚아챘다!$빼앗은 열매를 들고 재빨리 도망쳤다.",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/berries-abound-dialogue.json
> +      "selected": "강한 포켓몬과 상품을 남겨두고\n당신은 계속 나아간다."
```suggestion
      "selected": "강한 포켓몬과 열매를 남겨두고\n계속 나아갔다."
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +  "intro": "{{greedentName}}[[가]] 기습으로\n파티의 나무열매를 훔쳐갑니다!",
```suggestion
  "intro": "갑자기 나타난 {{greedentName}}[[가]]\n나무열매를 훔쳐갔다!",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +  "title": "절대적 탐욕",
```suggestion
  "title": "끝없는 욕심",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +  "description": "{greedentName}}[[는]] 당신을 완전히 방심하게 만들었습니다. 나무열매가 모두 사라져버렸습니다!\n\n{{greedentName}}[[가]] 나무열매를 먹으려다가 잠시 멈춰서 당신을 바라봅니다. 흥미롭네요.",
```suggestion
  "description": "{greedentName}}[[는]] 당신이 방심한 틈에 나무열매를 모두 훔쳐갔다!\n\n{{greedentName}}[[는]] 나무열매를 먹으려다 잠시 멈추고, 재미있다는 듯 쳐다보았다.",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +      "selected": "{{greedentName}}[[는]] 뺨을 채우고\n배틀을 준비한다!",
```suggestion
      "selected": "{{greedentName}}[[는]] 볼을 빵빵하게 채우고\n덤벼들었다!",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +      "boss_enraged": "{{greedentName}}[[는]] 식탐으로 불타오르고 있다!",
```suggestion
      "boss_enraged": "{{greedentName}}[[는]] 식탐으로 가득 차 있다!",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +      "food_stash": "{{greedentName}}[[는]] 엄청난 양의 음식을 지키고 있는 것 같다!$@s{item_fanfare}파티에 있는 포켓몬이 각각 {{foodReward}}[[를]] 얻는다!"
```suggestion
      "food_stash": "{{greedentName}}[[는]] 많은 음식을 가지고 있는 것 같다!$@s{item_fanfare}모든 포켓몬이 각각 {{foodReward}}[[를]] 얻었다!"
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +      "tooltip": "(+) 잃은 나무열매 일부를 재획득.",
```suggestion
      "tooltip": "(+) 빼앗긴 나무열매 일부를 돌려받음.",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +      "selected": "당신의 애원은 {{greedentName}}에게 깊은 인상을 남겼다.$모든 나무열매를 돌려주지는 않았지만, 몇 개를 이쪽으로 던졌다."
```suggestion
      "selected": "{{greedentName}}의 마음이 움직인 것 같다.$훔쳐간 나무열매 일부를 이쪽으로 던졌다."
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +      "label": "음식 먹게하기",
```suggestion
      "label": "먹게 두기",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +      "tooltip": "(-) 모든 나무열매를 잃음\n(?) {{greedentName}}[[가]] 당신을 좋아함.",
```suggestion
      "tooltip": "(-) 모든 나무열매를 잃음\n(?) {{greedentName}}[[가]] 매우 좋아함.",
```

2024-09-14 07:05 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +      "selected": "{{greedentName}}[[가]] 눈 깜짝할 새에\n모든 나무열매를 먹어치웠다!$흡족하게 이쪽을 바라보면서,\n배를 쓰다듬는다.$아마도 모험하면서\n나무열매를 더 먹여줘야할 것 같다…$@s{level_up_fanfare}{{greedentName}}[[는]] 동료가 되고 싶어하는 것 같다!"
```suggestion
      "selected": "{{greedentName}}[[가]] 눈 깜짝할 새에\n모든 나무열매를 먹어치웠다!$흡족하게 이쪽을 바라보면서,\n빵빵해진 배를 두드렸다.$아마 앞으로 식비가 만만치 않을 것 같다…$@s{level_up_fanfare}{{greedentName}}[[는]] 동료가 되고 싶어하는 것 같다!"
```

2024-09-14 07:21 UTC, KimJeongSun requested changes

2024-09-14 07:21 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/delibirdy-dialogue.json
> +  "description": "{{delibirdName}}들은 기대에 찬 눈빛으로 당신을 바라본다. 무언가를 원하는 것 같다. 혹시 아이템이나 돈을 주면 좋아할까?",
```suggestion
  "description": "{{delibirdName}}들의 눈이 초롱초롱하다. 뭔가 바라는 게 있는 것 같다. 혹시 아이템이나 돈을 원하는 걸까?",
```

2024-09-14 07:21 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/delibirdy-dialogue.json
> +      "selected": "당신이 돈을 건네니, {{delibirdName}}들은\n 신이나서 떠들어대기 시작했다.$그리고 당신에게 돌아와 행복하게 선물을 건넨다!"
```suggestion
      "selected": "당신이 돈을 건네니, {{delibirdName}}들은\n자기들끼리 신나서 떠들어댔다.$그리고 돌아와 웃으면서 선물을 건네 주었다!"
```

2024-09-14 07:21 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/delibirdy-dialogue.json
> +      "tooltip": "(-) {{delibirdName}}들에게 나무열매 또는 기적의씨 선물\n(+) 선물 아이템 획득",
```suggestion
      "tooltip": "(-) {{delibirdName}}들에게 나무열매나 기적의 씨를 줌 \n(+) 선물 아이템 획득",
```

2024-09-14 07:21 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/delibirdy-dialogue.json
> +      "selected": "당신이 {{chosenItem}}}[[를]] 건네니, {{delibirdName}}들은\n신이나서 떠들어대기 시작했다.$그리고 당신에게 돌아와 행복하게 선물을 건넨다!"
```suggestion
      "selected": "당신이 {{chosenItem}}}[[를]] 건네니, {{delibirdName}}들은\n자기들끼리 신나서 떠들어댔다.$그리고 돌아와 웃으면서 선물을 건네 주었다!"
```

2024-09-14 07:21 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/delibirdy-dialogue.json
> +      "selected": "당신이 {{chosenItem}}}[[를]] 건네니, {{delibirdName}}들은\n신이나서 떠들어대기 시작했다.$그리고 당신에게 돌아와 행복하게 선물을 건넨다!"
```suggestion
      "selected": "당신이 {{chosenItem}}}[[를]] 건네니, {{delibirdName}}들은\n자기들끼리 신나서 떠들어댔다.$그리고 돌아와 웃으면서 선물을 건네 주었다!"
```

2024-09-14 07:21 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/delibirdy-dialogue.json
> +      "tooltip": "(-) {{delibirdName}}들에게 지니고 있는 아이템 선물\n(+) 선물 아이템 획득",
```suggestion
      "tooltip": "(-) {{delibirdName}}들에게 지니고 있는 아이템을 줌\n(+) 선물 아이템 획득",
```

2024-09-14 07:21 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/delibirdy-dialogue.json
> +  "outro": "{{delibirdName}} 무리가 행복하게 뒤뚱거리며 저 멀리 날아간다.$정말 흥미로운 교환이었어!"
```suggestion
  "outro": "{{delibirdName}} 무리는 행복하게 뒤뚱거리며 떠났다.$정말 별난 거래였다!"
```

2024-09-14 17:35 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +      "boss_enraged": "{{greedentName}}[[는]] 식탐으로 불타오르고 있다!",
이건 제 원문이 더 나아서 걍 둡니다

2024-09-14 18:03 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +  "description": "{greedentName}}[[는]] 당신을 완전히 방심하게 만들었습니다. 나무열매가 모두 사라져버렸습니다!\n\n{{greedentName}}[[가]] 나무열매를 먹으려다가 잠시 멈춰서 당신을 바라봅니다. 흥미롭네요.",
```suggestion
  "description": "당신이 방심한 틈에 {greedentName}}[[가]] 나무열매를 모두 훔쳐가버렸습니다!\n\n{{greedentName}}[[는]] 나무열매를 먹으려다가, 잠시 멈춰서 당신을 재밌다는 듯 바라봅니다",
```

2024-09-14 18:13 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +  "query": "어떻게 할까?",
```suggestion
  "query": "어떻게 하시겠습니까?",
```

2024-09-14 18:13 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/berries-abound-dialogue.json
> +  "query": "어떻게 할까?",
```suggestion
  "query": "어떻게 하시겠습니까?",
```

2024-09-14 19:14 UTC, sodaMelon commented
1차 완료
# 참고
- 포켓몬도구는 명사로 모든 띄어쓰기를 붙여씁니다 ```예: 기적의씨```
- 딜리버드는 펭귄이지만 공중날기도 쓰고 날아다닙니다...

2024-09-15 13:40 UTC, KimJeongSun commented
https://github.com/user-attachments/assets/988fd7dc-d7d3-4340-bfc0-6241e3691dab


https://github.com/user-attachments/assets/290d6ee9-7fa5-487e-80ec-deb81b299f58


https://github.com/user-attachments/assets/8e325e5e-1acd-4d49-954d-1327f238654a

2024-09-15 13:40 UTC, merged

2024-09-15 13:44 UTC, sodaMelon commented
@KimJeongSun 디스코드 체크해주세요~