[event]mysterious chagllengers, field trip, lost at sea
pokerogue-KO/ME-KOREAN pull request #7
Opened 2024-09-13 20:13 UTC by sodaMelon

#미스터리한 도전자
![image](https://github.com/user-attachments/assets/27c587f4-fdc9-452b-9dca-f69f42e8d813)

#현장학습
![image](https://github.com/user-attachments/assets/8cc554ae-26de-4b06-8d28-b8edcb252f2b)

#바다위의 미아
![image](https://github.com/user-attachments/assets/ec66d9aa-9e1d-438f-90f8-edffcaf6abce)

2024-09-14 08:15 UTC, KimJeongSun requested changes
valuable 을 이질감이 적은 `좋은` 으로 번역하면서 뉘앙스를 살려봤습니다.

2024-09-14 08:15 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/field-trip-dialogue.json
> +  "intro_dialogue": "안녕하세요! 저희 학생들에게 잠시\n시간 좀 내주실 수 있을까요?$포켓몬의 기술에 대해서 가르치고 있는데\n실제 기술을 보게되면 좋아할 것 같아서요.$괜찮으시면 저희에게 포켓몬이\n사용할 수 있는 기술을 보여주실래요?",
```suggestion
  "intro_dialogue": "안녕하세요! 우리 학생들에게 잠시\n시간 좀 내주실 수 있을까요?$포켓몬 기술에 대해서 가르치고 있는데\n실제로 기술을 보면 좋아할 것 같아서요.$괜찮으시면 포켓몬이\n사용할 수 있는 기술을 보여주실래요?",
```

2024-09-14 08:15 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/field-trip-dialogue.json
> +  "description": "학교 선생님이 포켓몬의 기술 시연을 부탁했다. 선택한 기술에 따라, 선생님이 당신에게 유용한 것을 대가로 줄 수도 있을 것 같다.",
```suggestion
  "description": "학교 선생님이 포켓몬의 기술 시연을 부탁했다. 선택한 기술에 따라, 선생님이 뭔가 쓸 만한 걸 줄 수도 있을 것 같다.",
```

2024-09-14 08:15 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/field-trip-dialogue.json
> +  "incorrect": "...$이건 {{moveCategory}} 기술이 아니네요!\n죄송하지만, 아무것도 드릴 수 없어요.$여러분 이리오세요. 다른 곳에서\n더 좋은 기술 시연을 찾아서 보여드릴게요.",
```suggestion
  "incorrect": "...$이건 {{moveCategory}} 기술이 아닌데요!\n죄송하지만, 저희는 이만 가볼게요.$얘들아 이리오렴. 다른 곳에서는\n제대로된 기술 시연을 볼 수 있을거야.",
```

2024-09-14 08:15 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/field-trip-dialogue.json
> +  "incorrect_exp": "당신도 가치있는 실습(?)에서 배운 것 같다.$포켓몬도 약간의 경험치를 얻었다.",
```suggestion
  "incorrect_exp": "좋은 경험(?)을 한 것 같다.$포켓몬도 약간의 경험치를 얻었다.",
```

2024-09-14 08:15 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/field-trip-dialogue.json
> +  "correct": "친절하게 보여주셔서 감사합니다!\n이 아이템이 도움이 되시길 바랄게요!",
```suggestion
  "correct": "멋진 시연 감사합니다!\n이 아이템이 도움이 되시길 바랄게요!",
```

2024-09-14 08:15 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/field-trip-dialogue.json
> +  "correct_exp": "{{pokeName}}도 약간의 가치있는 경험치를 얻었다!",
```suggestion
  "correct_exp": "{{pokeName}}도 좋은 경험을 쌓았다!",
```

2024-09-14 12:54 UTC, KimJeongSun requested changes

2024-09-14 12:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/lost-at-sea-dialogue.json
> +  "intro": "목표없이 바다를 헤메다보니, 정말로 당신은 아무 데도 갈 수 없게 되었다.",
```suggestion
  "intro": "하염없이 바다를 떠돌다, 더이상 헤맬 곳조차 남지 않게 되었다.",
```

2024-09-14 12:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/lost-at-sea-dialogue.json
> +  "description": "이 지역의 바다는 난기류다. 그리고 당신은 에너지가 부족한 상태다.\n난감한 상황이다. 이 상황을 벗어날 수 있는 방법이 있을까?",
```suggestion
  "description": "이곳은 미지의 바다다. 그리고 점점 기력이 떨어지고 있다.\n난감한 상황이다. 이 상황을 벗어날 방법이 있을까?",
```

2024-09-14 12:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/lost-at-sea-dialogue.json
> +      "selected": "{{option1PrimaryName}}[[가]] 앞장서 헤엄치며, 돌아가는 길을 안내했다.${{option1PrimaryName}}[[는]] 역시 이번 기회로 더 강해진 것 같다!"
```suggestion
      "selected": "{{option1PrimaryName}}[[가]] 앞장서 헤엄치며, 돌아가는 길을 안내했다.${{option1PrimaryName}} 또한 이번 기회로 더 강해진 것 같다!"
```

2024-09-14 12:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/lost-at-sea-dialogue.json
> +      "selected": "{{option2PrimaryName}}[[가]] 보트 앞에서 날아가며, 돌아가는 길을 안내했다.${{option2PrimaryName}}[[는]] 이번 기회로 더 강해진 것 같다!"
```suggestion
      "selected": "{{option2PrimaryName}}[[가]] 보트 앞에서 날아가며, 돌아가는 길을 안내했다.${{option2PrimaryName}} 또한 기회로 더 강해진 것 같다!"
```

2024-09-14 12:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/lost-at-sea-dialogue.json
> +      "selected": "마침내 기억하는 랜드매크를 발견할 때까지, 당신은 정처없이 배를 조종하며 떠돌아다닌다.$포켓몬과 당신은 거대한 시련에 지쳐버렸다."
```suggestion
      "selected": "마침내 기억하는 곳에 다다를 때까지, 정처없이 배를 타고 떠돌아다닌다.$길고 긴 표류에 포켓몬과 당신 모두 지쳐버렸다."
```

2024-09-14 12:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/lost-at-sea-dialogue.json
> +  "outro": "당신은 다시 길 위로 돌아왔다."
```suggestion
  "outro": "다시 여정으로 돌아왔다."
```

2024-09-14 12:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/mysterious-challengers-dialogue.json
> +  "intro": "미스터리한 도전자들이 나타났다!",
```suggestion
  "intro": "수수께끼의 도전자들이 나타났다!",
```

2024-09-14 12:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/mysterious-challengers-dialogue.json
> +  "title": "미스터리한 도전자",
```suggestion
  "title": "수수께끼의 도전자",
```

2024-09-14 12:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/mysterious-challengers-dialogue.json
> +  "outro": "미스터리한 도전자에게 승리했다!"
```suggestion
  "outro": "수수께끼의 도전자를 물리쳤다!"
```

2024-09-14 12:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/mysterious-challengers-dialogue.json
> +    "selected": "트레이너가 앞으로 나아간다..."
```suggestion
    "selected": "선택한 트레이너가 앞으로 걸어나온다..."
```

2024-09-14 12:54 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/mysterious-challengers-dialogue.json
> +  "description": "도전자에게 승리한다면, 보상 받을만큼 깊은 인상을 남길 수 있다. 몇몇 도전자들은 꽤 강해보이기도 한다. 도전을 받아줄까?",
```suggestion
  "description": "도전자에게 승리해서 깊은 인상을 남긴다면, 보상을 받을 수 있을 것 같다. 몇몇 도전자들은 꽤 강해보인다. 도전을 받아줄까?",
```

2024-09-14 18:47 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/field-trip-dialogue.json
> +  "incorrect": "...$이건 {{moveCategory}} 기술이 아니네요!\n죄송하지만, 아무것도 드릴 수 없어요.$여러분 이리오세요. 다른 곳에서\n더 좋은 기술 시연을 찾아서 보여드릴게요.",
```suggestion
  "incorrect": "...$이건 {{moveCategory}} 기술이 아닌데요!\n죄송하지만, 저희는 이만 가볼게요.$얘들아 이리오렴. 다른 곳에서는\n제대로된 기술 시연을 볼 수 있을거야.",
```

2024-09-15 15:19 UTC, KimJeongSun commented
https://github.com/user-attachments/assets/d32a27b6-0be5-4c86-a272-a7f6ae5a9ec2


https://github.com/user-attachments/assets/2fe95eff-d1c2-4eb5-9fea-41d7391167b0


https://github.com/user-attachments/assets/65c68940-12bd-4ae4-8faf-5369a93174d7

2024-09-15 15:19 UTC, merged